### ISSUE TITLE
ability to username and password authentication in MQTT-TLS

### ISSUE THREAD

**Issue by saket424** [hirotakaster/MQTT-TLS#10]
@hirotakaster 
Is there a way to specify the username and password when connecting to an MQTT-TLS broker ?
Your example does not currently allow for this unless I missed it
Thanks

**Comment by hirotakaster** [comment]
use this method.
bool MQTT::connect(const char *id, const char *user, const char *pass);

**Comment by saket424** [comment]
I get the following error

mqtts.ino:90:53: cannot call member function 'bool MQTT::connect(const char*, const char*, const char*)' without object

When I try to include MQTT libraries in an MQTT-TLS project I get redefinition errors

Can you enhance the MQTT-TLS example1 to include username and password?
