### ISSUE TITLE
Un-verified connections possible (MITM risk)

### ISSUE THREAD

**Issue by Phsacar** [hirotakaster/MQTT-TLS#12]
Hi,

in MQTT-TLS.cpp you have a section where you allow un-verified connections. See:
`    // if server certificates is not valid, connection will success. check certificates on verify() function.
    mbedtls_ssl_conf_authmode(&conf, MBEDTLS_SSL_VERIFY_OPTIONAL);
    mbedtls_ssl_conf_rng(&conf, &MQTT::rng_Tls, nullptr);
mbedtls_ssl_conf_ca_chain(&conf, &cacert, nullptr);`

I can understand that you want your library to be as user friendly as possible, however this is a huge risk if you are using username/password verification during login. (MITM is possible) The problem here is, that you can not call verify() before logging in. ( Your connect routine has no option for doing so )

Please add an option for enforced verification.

Thanks,
phsacar

**Comment by hirotakaster** [comment]
Hi @Phsacar ,

> Please add an option for enforced verification.

Ah, nice idea. I know VERIFY_[NONE|OPTIONAL|REQUIRED] when TLS handshake process, and I hesitated about it have to separate TLS and MQTT sequence or not.
I would think about the this option setting on this library(function argument or header file...etc).

Thank you.
