### ISSUE TITLE
sha1.h/sha1.cpp missing

### ISSUE THREAD

**Issue by asterix555** [hirotakaster/MQTT-TLS#16]
Hi Hirotaka-san,

Just updated to the most recent mqtt-tls version but saw a compile-error. Seems that the sha1.h (and sha1.cpp) are not included in the rep?!

I downloaded the files from your TlsTcpClient and everything went fine:
https://github.com/hirotakaster/TlsTcpClient/tree/master/src

kind regards

**Comment by hirotakaster** [comment]
Thank you. I forgot it. Now I add SHA1 files.
