### ISSUE TITLE
MQTT client goes to infinite loop when there is a MQTT broker disconnect/restart and never recovers

### ISSUE THREAD

**Issue by sriharsha-rbnd** [hirotakaster/MQTT-TLS#21]
Hi,

I am trying to debug an issue in the TLS library on Particle P1 chip. I am running a mosquitto MQTT broker on AWS EC2 linux instance with TLS enabled on one of the listening port with certificates from letsencrypt. I have used a1-example.ino from your latest 0.2.18 library version. The connectivity to MQTT broker is fine and the MQTT client can publish and subscribe messages to and from MQTT broker without any issue. Only when the broker listening port is shutdown or the broker is restarted, the MQTT client on Particle P1 goes to infinite while loop. 

On further debugging, I found that readPacket() function called during client.loop() path, calls readByte() function multiple times. On first call to the function readByte(), it receives MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY message from the broker and calls disconnect() with returning -1 to readPacket(). readPacket() does not test this -1 return and calls readByte() again. This time readByte() goes to infinite while loop waiting for data on the tcpClient stream which was previously disconnected.

I am attaching the debug prints I added to readByte() call just to confirm the infinite loop scenario. Even if the broker is restarted, the MQTT client can never recover from this scenario. Please help to resolve this issue as I have limited knowledge on TCP and SSL protocol.

`

    uint8_t MQTT::readByte() {
        if (tls == false) {
    #if 1
            /* Debug code */
            int count = 0;
            do
            {
                if ((count = tcpClient.available()) == 0)
                {
                    Serial.print("l ");
                }
            } while (!count);
    #else
            while(!tcpClient.available()) {}
    #endif            
            return tcpClient.read();
        } else {
            uint8_t val = 0;
            uint8_t buff;

            if (tlsConnected) {
                while (1) {
                    int ret = mbedtls_ssl_read(&ssl, &buff, 1);
                    if (ret < 0) {
                          switch (ret) {
                            case MBEDTLS_ERR_SSL_WANT_READ:
                              break;
                          case MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE:
                              Serial.printlnf("readByte():ssl unexpected message\n");
                          case MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY:
                              Serial.printlnf("readByte():peer close notiy/error\n");
                          default:
                              Serial.printlnf("readByte():Calling disconnect\n");
                              disconnect();
                              return -1;
                        }
                    } else {
                        return buff;
                    }
                }
            } else {
                return -1;
            }
        }
    }

`

**Comment by sriharsha-rbnd** [comment]
Hi,

@hirotakaster, issue mentioned above is specific to MQTT-TLS library and it is not observed on non-TLS version of your library (MQTT). That mostly rules out Particle TCP stack from the suspect list I suppose. Please look into readPacket() and readByte() functions implementation. The return value of -1 in readByte() has to be handled properly in readPacket() when there is a broker disconnect and mbedtls_ssl_read() notifies the same.

Your inputs to resolve this issue is very much appreciated. Thanks.

**Comment by sriharsha-rbnd** [comment]
Hi,

@hirotakaster The issue reported here is same as reported in #9. It was wrongly diagnosed as issue with client.isConnected() suspecting Particle TCPClient stack. Below is the code for isConnected() from the MQTT-TLS library. 

    bool MQTT::isConnected() {
        bool rc = (int)tcpClient.connected();
        if (tls)
            return tlsConnected;
        return rc;
    }

Some observations on above code:
1. Above function will always return status of tlsConnected if tls was enabled by enableTls() call. tlsConnected will return true untils disconnect() is called and tlsConnected is set as false.

2. Also refer to Particle's documentation for [connected()](https://docs.particle.io/reference/firmware/photon/#connected-):
Unless the data on the TCPClient stream is read, the tcp connection is still seen as connected even if the server has closed its connection to client.
> connected()
Whether or not the client is connected. Note that a client is considered connected if the connection has been closed but there is still unread data.
Returns true if the client is connected, false if not.

Above mentioned observations rules out issue with Particle's TCPClient class. Issue has to be resolved in readPacket() of MQTT-TLS library which is not handling -1 return from readByte() properly.

**Comment by hirotakaster** [comment]
Hi @sriharsha-rbnd 
Thanks for your report. I will update to next version.

**Comment by hirotakaster** [comment]
Hi @sriharsha-rbnd 
now update to 0.2.19. here is sample code.
```
void loop() {
    if (client.isConnected()) {
        Serial.println("connected!!");
        client.loop();
        
    } else {
        client.disconnect();
        client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
        client.connect("sparkclient");
        if (client.isConnected())
            client.subscribe("inTopic/message");
    }
    delay(1000);
}
```

**Comment by sriharsha-rbnd** [comment]
Hi @hirotakaster,

Thank you for the fix. It works well. I am closing the issue.
