### ISSUE TITLE
Particle Lib broken...?

### ISSUE THREAD

**Issue by jeroensis** [hirotakaster/MQTT-TLS#24]
When trying to add the library to a project in the Web IDE, the icon keeps spinning indefinitely and the lib never get's added. Seems like the lib is damaged?
Maybe you can resubmit it?

**Comment by jeroensis** [comment]
Issue seems to only happen in Safari. Chrome does seem to work fine...

**Comment by jeroensis** [comment]
Stuck on compile errors (also made post on particle community):

lib/MQTT-TLS/mbedtls/md_internal.h:47:8: type 'struct mbedtls_md_info_t' violates one definition rule [-Werror=odr]
mbedtls/library/cipher_wrap.c:1349:35: type of 'mbedtls_cipher_definitions' does not match original declaration [-Werror]
mbedtls/library/cipher_wrap.c:1449:5: type of 'mbedtls_cipher_supported' does not match original declaration [-Werror]

Any advise would be appreciated...

**Comment by hirotakaster** [comment]
@jeroensis 
This is not issue about the this library. I could compile on Chrome WebIDE on particle, local IDE(VScode). If you could not compile on Safari, you use Chrome or VScode.

**Comment by jeroensis** [comment]
On Chrome. But meanwhile found out it is related to the Core. When I select photon it compiles. However I only have (many) Core devices.
It has been suggested that the Core is not supported?

**Comment by hirotakaster** [comment]
@jeroensis 
My 2 Particle Core was broken at a long time ago, so I can't test it. But 0.1.1 version was compile and use on Core. If you really want to use Core with MQTT-TLS, use 0.1.1 version.

**Comment by jeroensis** [comment]
Thanks. 
Also tried 0.1.1 but the last two error are still present:

mbedtls/library/cipher_wrap.c:1349:35: type of 'mbedtls_cipher_definitions' does not match original declaration [-Werror]
mbedtls/library/cipher_wrap.c:1449:5: type of 'mbedtls_cipher_supported' does not match original declaration [-Werror]

But will change to an Argon, not a big problem... (thanks for the help:)

**Comment by hirotakaster** [comment]
OK
