### ISSUE TITLE
Handshake errors in ProtocolError DTLSMessageChannel::establish()

### ISSUE THREAD

**Issue by BrandonVarner** [hirotakaster/MQTT-TLS#26]
We are running library version 0.2.20 on a Particle Argon board. We keep running into an error establishing the handshake. We do not run into this issue when we run the example code of Tinker on the board (which does not have the MQTT-TLS library). 

Have you seen any conflicting issues with the Argon's using your library? We are running deviceOS 1.3.0-rc.1.

**Comment by hirotakaster** [comment]
Hi @BrandonVarner ,
When you use firmware version 1.3.0-rc1 with MQTT-TLS, what established the handshake error is shown?
This library don't use DTLS(firmware and particle use DTLS).

When you use other version firmware, that error is shown?

**Comment by hirotakaster** [comment]
Now I check my Argon firmware 1.3.0-rc1 with MQTT-TLS 0.2.20, it works well on AWS IoT and mqtt.eclipse.org.

**Comment by BrandonVarner** [comment]
Hi @hirotakaster,
Thanks for the quick reply. I tried removing your library from the program and am running into the same issue with

0000073615 [system] INFO: Cloud socket connected
0000073616 [system] INFO: Starting handshake: presense_announce=0
0000073618 [comm.protocol.handshake] INFO: Establish secure connection
0000073725 [app] WARN: Cloud disconnected
0000073914 [comm.dtls] INFO: (CMPL,RENEG,NO_SESS,ERR) restoreStatus=2

So it must be within the OS changes in Particle. It only happens after I connect then remove power from the Argon and then try to connect. Something about handling sessions I’m guessing. I’ll reach out to Particle for support.

Thanks you,
Brandon

**Comment by hirotakaster** [comment]
@BrandonVarner 
Okay. Your application problem is unrelated with this library, maybe particle API or firmware issue.
