### ISSUE TITLE
Possible initialisation error here

### ISSUE THREAD

**Issue by ScruffR** [hirotakaster/MQTT-TLS#28]
Hi there, I've just gone through a project of mine cleaning up some warnings and stumbled across this 

https://github.com/hirotakaster/MQTT-TLS/blob/master/src/MQTT-TLS.cpp#L402
```
 memset(buffer, 0, sizeof(buffer));
```

The compiler suspected a potential problem and I tend to agree.

I would suspect you want to clear the entire buffer but that instruction only clears the first four bytes since `sizeof(buffer)` is `sizeof(uint8_t*)` which is just the pointer *not* the buffer as such.

**Comment by hirotakaster** [comment]
@ScruffR 
Oh... you are right!!
I will update.

**Comment by hirotakaster** [comment]
Thanks @ScruffR 
now update&release to particle contribute lib.
