### ISSUE TITLE
Reducing MQTT-TLS memory footprint

### ISSUE THREAD

**Issue by SubniC** [hirotakaster/MQTT-TLS#6]
I've been working on a project that uses MQTT-TLS lib with photon for an IoT device, at the beginning I found some problems getting it working because of the memory limitations of photon.

I was able to run MQTT with TLS support in an example code with no other functionality, but when I try to integrate the code in my project it was not able to run due to an insufficient memory amount (more information https://community.particle.io/t/mqtt-tls-on-photon-am-i-running-out-of-memory/39430)

At the end I realize that the mbedtls lib that is being used by @hirotakaster has a config.h file that allow to tweak some parameters, after some time testing I found the parameter `MBEDTLS_SSL_MAX_CONTENT_LEN`.

MBEDTLS_SSL_MAX_CONTENT_LEN defines the internal I/O buffers of the library, the constant is defined as 16Kb, which is the default required value for TLS, but if you control both ends of the connection you can reduce the buffer, in my test environment, I am able to work without any problem with values down to 4Kb.

At the time of writing I'm using a 8Kb value that works like a charm and give me plenty of memory for the rest of my code (including 16Khz audio samplig and processing, 12 neopixels and a bunch of i2c and serial sensors.

For more information take a look here: https://tls.mbed.org/kb/how-to/reduce-mbedtls-memory-and-storage-footprint

hope this help :)

**Comment by hirotakaster** [comment]
Hi @SubniC ,

Thank you for your testing & reports!!
I will test "MBEDTLS_SSL_MAX_CONTENT_LEN 8192" on my Photon, if it's no problem I would update to next version.

**Comment by hirotakaster** [comment]
Hi @SubniC ,

Now update to 0.2.11.
This version could work on 0.6.x/0.7.x/0.8.x firmware :)

Thank you.
