### ISSUE TITLE
Missing member initialization?

### ISSUE THREAD

**Issue by pavel-benes** [hirotakaster/MQTT-TLS#7]
Hi,

I am using MQTT  class in my project for Particle Electron for some time.  When I was using this class as object member within my class, like this:

_class MyClass {
...
MQTT mqttClient;
...
}_

everything was fine. However when I have changed it to a pointer, like this:

_class MyClass {
...
MQTT* mqttClient;
...
}_

things got ugly. Sometimes it did not connected, sometimes it even crashed. The only difference was location of the memory area used for the instance. In the first case it resided on stack whereas in the second case it was allocated on the heap.  
My very first theory was, that memory got corrupted by some stray pointer, but now I rather believe that some MQTT class members (or members of their members) might not be properly initialized so the execution actually depends on the previous content of the allocated memory block.  

To test this I have overridden the 'new' operator of the MQTT class, like this:

_void* operator new(size_t size) {
        void *p = malloc(size);
        memset(p, 0, size);
        return p;
}_

 and the problem really disappeared. Have you seen similar behavior?

Thanks a lot,

Regards,
Pavel

**Comment by hirotakaster** [comment]
Here is MQTT-TLS repo.
bug fixed is there.
https://github.com/hirotakaster/MQTT/commit/451b1b84b41529b85d45c132f1d9dacd273093c5

**Comment by hirotakaster** [comment]
hi @pavel-benes ,
bug fixed version 0.2.12 published.

**Comment by pavel-benes** [comment]
Hi,
thank you very much for quick response. I will test it and let you know in case it did not help in my scenario.

Regards,
Pavel
