### ISSUE TITLE
Photon Breaths Green after MQTT TLS server connection is lost. (Program halted)

### ISSUE THREAD

**Issue by SkyGanfor** [hirotakaster/MQTT-TLS#9]
Hi,
I recently discovered an issue where the photon goes into a state of breathing green (not connected to wifi) when a TLS MQTT server connection is lost or terminated. The photons program is completely halted and will not continue after disconnected. Manually resetting the device with the physical rest button is the only way to fix this problem, but is temporary until connection is lost again.

I've been using the a1-example.ino program in my testing and I did not alter any of the program (only changes I made where the server address, client name, username, password, and certification file naturally). I also commented out the "RGB.control(true);" in order to see the photons device mode.

I've narrowed the problem down to "client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));" line of code. Without this line, this problem disappears entirely, but when the line is present, the problem persists. 

You can replicate this issue by using the a1 example file, connecting to a tls mqtt server, and terminating the mqtt server connection. Few seconds after the termination, the photon will breath green.

**Comment by hirotakaster** [comment]
what's firmware photon version you use?
On my test my two photon on 0.8.x, 0.7.x 0.6.3(default)  firmware working well.

**Comment by SkyGanfor** [comment]
I checked and I am using the 0.6.3 (default) firmware on my photon. 
I recorded a video of the issue and you can watch it here:
https://www.youtube.com/watch?v=cy4Wvi85Wlc&feature=youtu.be

**Comment by saket424** [comment]
@SkyGanfor,
I am observing breathing green and sometimes breathing blue also. I am not exactly clear why it gets into this state as I am not stopping the mqtt broker or anything as drastic. If you disable client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));" line of code, how are you able to connect to port 8883?

**Comment by saket424** [comment]
https://github.com/rickkas7/particle_notes/blob/master/breathing-green/README.md

I wonder if we have to periodically tickle Particle cloud to keep it from getting into the breathing green state. It works most of the time breathing cyan but sometimes gets into breathing green for no obvious reason

**Comment by hirotakaster** [comment]
I guess maybe @SkyGanfor want to say "Why MQTT state will "connected" even if stop the mosquitto on Windows?", that result would be depended on Windows mosquitto implementation or (Photon or Windows) TCP stack.
Check the TCP packet with WireShark or tcpdump.

Usually, TCP server implements disconnect the client when server process end with TCP(FIN). And next, client TCP stack detect the TCP connection finish. On this MQTT-TLS library isConnected method check the Particle firmware stack TCPClient state. If Particle firmware TCP stack don't detect the TCP end(FIN) or Windows mosquitto don't disconnect the client TCP connection(or Windows TCP stack?) isConnected method return the true.

And this library send a keep alive packet every 15 sec, when it don't get the keep alive packet with server(or Particle TCP keep alive timeout occur), isConnected will be false.

**Comment by saket424** [comment]
My breathing green issue got narrowed down to multiple devices using the same client id. When each device uses a unique client id, all is well

**Comment by saket424** [comment]
In my case when device went into breathing green state due to client name conflict, it was not executing the main loop any more and only recourse was to cycle power to it. 
@hirotaka, is it required that client name has to be unique?

**Comment by hirotakaster** [comment]
@saket424 unique is needed. you could use photon mac address as client id for unique.

**Comment by SkyGanfor** [comment]
Here is the code I'm using. Its the default "a1-example.ino" file with some slight modifications.

`#include "MQTT-TLS.h"

void callback(char* topic, byte* payload, unsigned int length);

#define LET_ENCRYPT_CA_PEM                                              \
"-----BEGIN CERTIFICATE----- \r\n"                                      \
"MIID7zCCAtegAwIBAgIJAJZwRCk+7YG4MA0GCSqGSIb3DQEBCwUAMIGMMQswCQYD\r\n"  \
"VQQGEwJVUzERMA8GA1UECAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRz\r\n"  \
"MQwwCgYDVQQKDANHVkExDDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRN\r\n"  \
"LmNvbTEgMB4GCSqGSIb3DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wIBcNMTgwMzAy\r\n"  \
"MTY1MTEzWhgPMjA2ODAyMTgxNjUxMTNaMIGMMQswCQYDVQQGEwJVUzERMA8GA1UE\r\n"  \
"CAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRzMQwwCgYDVQQKDANHVkEx\r\n"  \
"DDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRNLmNvbTEgMB4GCSqGSIb3\r\n"  \
"DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\r\n"  \
"ggEKAoIBAQDYoUySKC7oaQqRfxCL3kbS7/g+cCTYlePwB5Ooj9bOfS624vs6qRF6\r\n"  \
"j3O5ADCBw7jcVH/BAa2Rhy0hpKZIREKTl2+0jHrHfGJaIXTx1UNwmFfejWKxGiAB\r\n"  \
"ZVYm6RwX6GXNbLbEhgZo1wDzvki4teckt62FYk1OEGCAXW13G8OZpYC7uLQTbhPb\r\n"  \
"KZpYuvS2WXeqjEHGzjqn2q3Pjzq3vODamYOgjeTgd+1S+MjV+1fY0Z8iXj2T8g67\r\n"  \
"vl+gncoc+bjFb8TAPvChL9NqXFXjathE2GJ31XyMmcTThOf7jH5qO4JTQAHwNaad\r\n"  \
"dvlTN/V4JDj5irSYOv+XPjjRTPk2LUpZAgMBAAGjUDBOMB0GA1UdDgQWBBRHjzkn\r\n"  \
"oaDC9Pi7CGTgCsaU8bCNFDAfBgNVHSMEGDAWgBRHjzknoaDC9Pi7CGTgCsaU8bCN\r\n"  \
"FDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBiCMjZRz1qWt2E50bl\r\n"  \
"uU29zwxlodTSeQfQw9p6h9Fw6nEsC0HVU+3zmqtFStv9Azks+OQpAx2rjhqf7E2i\r\n"  \
"hE6+kaZu07qf0LtGK2YonvYu/t19ssXol45BScZqYEwsT2hOrDQLdj3I8UjE0oE8\r\n"  \
"Q66IozSdYwEEoCSb28ybWf4H5K8gaWgN+4YX7bsZGY2KxNodtVKG37y8ZAVsDQ4Y\r\n"  \
"7jF+DGARFfMWJgFn2JgG5CZU007ESpz4NPecuTraAMUjjp8uaJBrRbQOP+HX+kLX\r\n"  \
"q7q/4PMyY31Byj7nD4WBDGDwFi3m2GmBSgVfcuLhzK8rIYVVUNYWNMnxvWz6PdB0\r\n"  \
"XNBE\r\n"  \
"-----END CERTIFICATE----- "
const char letencryptCaPem[] = LET_ENCRYPT_CA_PEM;

/**
 * if want to use IP address,
 * byte server[] = { XXX,XXX,XXX,XXX };
 * MQTT client(server, 1883, callback);
 * want to use domain name,
 * MQTT client("www.sample.com", 1883, callback);
 * iot.eclipse.org is Eclipse Open MQTT Broker: https://iot.eclipse.org/getting-started
**/
MQTT client("VDMSW.VDM.com", 8883, callback);

// recieve message
void callback(char* topic, byte* payload, unsigned int length) {
    char p[length + 1];
    memcpy(p, payload, length);
    p[length] = NULL;
    String message(p);

    if (message.equals("RED"))
        RGB.color(255, 0, 0);
    else if (message.equals("GREEN"))
        RGB.color(0, 255, 0);
    else if (message.equals("BLUE"))
        RGB.color(0, 0, 255);
    else
        RGB.color(255, 255, 255);
    delay(1000);
}

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }

    //RGB.control(true);

    // enable tls. set Root CA pem file.
    // if you don't use TLS, comment out this line.
    client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
    Serial.println("tls enable");

    // connect to the server
    client.connect("sparkclient");

    // publish/subscribe
    if (client.isConnected()) {
        Serial.println("client connected");
        client.publish("outTopic/message", "hello world");
        client.subscribe("inTopic/message");
    }
}

void loop() {
    if (client.isConnected())
    {
        client.loop();
        Serial.println("Connected!");
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}`

**Comment by SkyGanfor** [comment]
Here is my code, which is the "a1-example.ino" program with some slight modifications:

```
#include "MQTT-TLS.h"

void callback(char* topic, byte* payload, unsigned int length);

#define LET_ENCRYPT_CA_PEM                                              \
"-----BEGIN CERTIFICATE----- \r\n"                                      \
"MIID7zCCAtegAwIBAgIJAJZwRCk+7YG4MA0GCSqGSIb3DQEBCwUAMIGMMQswCQYD\r\n"  \
"VQQGEwJVUzERMA8GA1UECAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRz\r\n"  \
"MQwwCgYDVQQKDANHVkExDDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRN\r\n"  \
"LmNvbTEgMB4GCSqGSIb3DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wIBcNMTgwMzAy\r\n"  \
"MTY1MTEzWhgPMjA2ODAyMTgxNjUxMTNaMIGMMQswCQYDVQQGEwJVUzERMA8GA1UE\r\n"  \
"CAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRzMQwwCgYDVQQKDANHVkEx\r\n"  \
"DDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRNLmNvbTEgMB4GCSqGSIb3\r\n"  \
"DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\r\n"  \
"ggEKAoIBAQDYoUySKC7oaQqRfxCL3kbS7/g+cCTYlePwB5Ooj9bOfS624vs6qRF6\r\n"  \
"j3O5ADCBw7jcVH/BAa2Rhy0hpKZIREKTl2+0jHrHfGJaIXTx1UNwmFfejWKxGiAB\r\n"  \
"ZVYm6RwX6GXNbLbEhgZo1wDzvki4teckt62FYk1OEGCAXW13G8OZpYC7uLQTbhPb\r\n"  \
"KZpYuvS2WXeqjEHGzjqn2q3Pjzq3vODamYOgjeTgd+1S+MjV+1fY0Z8iXj2T8g67\r\n"  \
"vl+gncoc+bjFb8TAPvChL9NqXFXjathE2GJ31XyMmcTThOf7jH5qO4JTQAHwNaad\r\n"  \
"dvlTN/V4JDj5irSYOv+XPjjRTPk2LUpZAgMBAAGjUDBOMB0GA1UdDgQWBBRHjzkn\r\n"  \
"oaDC9Pi7CGTgCsaU8bCNFDAfBgNVHSMEGDAWgBRHjzknoaDC9Pi7CGTgCsaU8bCN\r\n"  \
"FDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBiCMjZRz1qWt2E50bl\r\n"  \
"uU29zwxlodTSeQfQw9p6h9Fw6nEsC0HVU+3zmqtFStv9Azks+OQpAx2rjhqf7E2i\r\n"  \
"hE6+kaZu07qf0LtGK2YonvYu/t19ssXol45BScZqYEwsT2hOrDQLdj3I8UjE0oE8\r\n"  \
"Q66IozSdYwEEoCSb28ybWf4H5K8gaWgN+4YX7bsZGY2KxNodtVKG37y8ZAVsDQ4Y\r\n"  \
"7jF+DGARFfMWJgFn2JgG5CZU007ESpz4NPecuTraAMUjjp8uaJBrRbQOP+HX+kLX\r\n"  \
"q7q/4PMyY31Byj7nD4WBDGDwFi3m2GmBSgVfcuLhzK8rIYVVUNYWNMnxvWz6PdB0\r\n"  \
"XNBE\r\n"  \
"-----END CERTIFICATE----- "
const char letencryptCaPem[] = LET_ENCRYPT_CA_PEM;

/**
 * if want to use IP address,
 * byte server[] = { XXX,XXX,XXX,XXX };
 * MQTT client(server, 1883, callback);
 * want to use domain name,
 * MQTT client("www.sample.com", 1883, callback);
 * iot.eclipse.org is Eclipse Open MQTT Broker: https://iot.eclipse.org/getting-started
**/
MQTT client("VDMSW.VDM.com", 8883, callback);

// recieve message
void callback(char* topic, byte* payload, unsigned int length) {
    char p[length + 1];
    memcpy(p, payload, length);
    p[length] = NULL;
    String message(p);

    if (message.equals("RED"))
        RGB.color(255, 0, 0);
    else if (message.equals("GREEN"))
        RGB.color(0, 255, 0);
    else if (message.equals("BLUE"))
        RGB.color(0, 0, 255);
    else
        RGB.color(255, 255, 255);
    delay(1000);
}

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }

    //RGB.control(true);

    // enable tls. set Root CA pem file.
    // if you don't use TLS, comment out this line.
    client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
    Serial.println("tls enable");

    // connect to the server
    client.connect("sparkclient");

    // publish/subscribe
    if (client.isConnected()) {
        Serial.println("client connected");
        client.publish("outTopic/message", "hello world");
        client.subscribe("inTopic/message");
    }
}

void loop() {
    if (client.isConnected())
    {
        client.loop();
        Serial.println("Connected!");
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}
```

**Comment by SkyGanfor** [comment]
Here is my code, which is the "a1-example.ino" program with some slight modifications:

#include "MQTT-TLS.h"

void callback(char* topic, byte* payload, unsigned int length);

#define LET_ENCRYPT_CA_PEM                                              \
"-----BEGIN CERTIFICATE----- \r\n"                                      \
"MIID7zCCAtegAwIBAgIJAJZwRCk+7YG4MA0GCSqGSIb3DQEBCwUAMIGMMQswCQYD\r\n"  \
"VQQGEwJVUzERMA8GA1UECAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRz\r\n"  \
"MQwwCgYDVQQKDANHVkExDDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRN\r\n"  \
"LmNvbTEgMB4GCSqGSIb3DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wIBcNMTgwMzAy\r\n"  \
"MTY1MTEzWhgPMjA2ODAyMTgxNjUxMTNaMIGMMQswCQYDVQQGEwJVUzERMA8GA1UE\r\n"  \
"CAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRzMQwwCgYDVQQKDANHVkEx\r\n"  \
"DDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRNLmNvbTEgMB4GCSqGSIb3\r\n"  \
"DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\r\n"  \
"ggEKAoIBAQDYoUySKC7oaQqRfxCL3kbS7/g+cCTYlePwB5Ooj9bOfS624vs6qRF6\r\n"  \
"j3O5ADCBw7jcVH/BAa2Rhy0hpKZIREKTl2+0jHrHfGJaIXTx1UNwmFfejWKxGiAB\r\n"  \
"ZVYm6RwX6GXNbLbEhgZo1wDzvki4teckt62FYk1OEGCAXW13G8OZpYC7uLQTbhPb\r\n"  \
"KZpYuvS2WXeqjEHGzjqn2q3Pjzq3vODamYOgjeTgd+1S+MjV+1fY0Z8iXj2T8g67\r\n"  \
"vl+gncoc+bjFb8TAPvChL9NqXFXjathE2GJ31XyMmcTThOf7jH5qO4JTQAHwNaad\r\n"  \
"dvlTN/V4JDj5irSYOv+XPjjRTPk2LUpZAgMBAAGjUDBOMB0GA1UdDgQWBBRHjzkn\r\n"  \
"oaDC9Pi7CGTgCsaU8bCNFDAfBgNVHSMEGDAWgBRHjzknoaDC9Pi7CGTgCsaU8bCN\r\n"  \
"FDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBiCMjZRz1qWt2E50bl\r\n"  \
"uU29zwxlodTSeQfQw9p6h9Fw6nEsC0HVU+3zmqtFStv9Azks+OQpAx2rjhqf7E2i\r\n"  \
"hE6+kaZu07qf0LtGK2YonvYu/t19ssXol45BScZqYEwsT2hOrDQLdj3I8UjE0oE8\r\n"  \
"Q66IozSdYwEEoCSb28ybWf4H5K8gaWgN+4YX7bsZGY2KxNodtVKG37y8ZAVsDQ4Y\r\n"  \
"7jF+DGARFfMWJgFn2JgG5CZU007ESpz4NPecuTraAMUjjp8uaJBrRbQOP+HX+kLX\r\n"  \
"q7q/4PMyY31Byj7nD4WBDGDwFi3m2GmBSgVfcuLhzK8rIYVVUNYWNMnxvWz6PdB0\r\n"  \
"XNBE\r\n"  \
"-----END CERTIFICATE----- "
const char letencryptCaPem[] = LET_ENCRYPT_CA_PEM;

/**
 * if want to use IP address,
 * byte server[] = { XXX,XXX,XXX,XXX };
 * MQTT client(server, 1883, callback);
 * want to use domain name,
 * MQTT client("www.sample.com", 1883, callback);
 * iot.eclipse.org is Eclipse Open MQTT Broker: https://iot.eclipse.org/getting-started
**/
MQTT client("myservername", 8883, callback);

// recieve message
void callback(char* topic, byte* payload, unsigned int length) {
    char p[length + 1];
    memcpy(p, payload, length);
    p[length] = NULL;
    String message(p);

    if (message.equals("RED"))
        RGB.color(255, 0, 0);
    else if (message.equals("GREEN"))
        RGB.color(0, 255, 0);
    else if (message.equals("BLUE"))
        RGB.color(0, 0, 255);
    else
        RGB.color(255, 255, 255);
    delay(1000);
}

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }

    //RGB.control(true);

    // enable tls. set Root CA pem file.
    // if you don't use TLS, comment out this line.
    client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
    Serial.println("tls enable");

    // connect to the server
    client.connect("sparkclient");

    // publish/subscribe
    if (client.isConnected()) {
        Serial.println("client connected");
        client.publish("outTopic/message", "hello world");
        client.subscribe("inTopic/message");
    }
}

void loop() {
    if (client.isConnected())
    {
        client.loop();
        Serial.println("Connected!");
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}

**Comment by SkyGanfor** [comment]
Here is my code, which is the "a1-example.ino" program with some slight modifications:
```
#include "MQTT-TLS.h"

void callback(char* topic, byte* payload, unsigned int length);

#define LET_ENCRYPT_CA_PEM                                              \
"-----BEGIN CERTIFICATE----- \r\n"                                      \
"MIID7zCCAtegAwIBAgIJAJZwRCk+7YG4MA0GCSqGSIb3DQEBCwUAMIGMMQswCQYD\r\n"  \
"VQQGEwJVUzERMA8GA1UECAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRz\r\n"  \
"MQwwCgYDVQQKDANHVkExDDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRN\r\n"  \
"LmNvbTEgMB4GCSqGSIb3DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wIBcNMTgwMzAy\r\n"  \
"MTY1MTEzWhgPMjA2ODAyMTgxNjUxMTNaMIGMMQswCQYDVQQGEwJVUzERMA8GA1UE\r\n"  \
"CAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRzMQwwCgYDVQQKDANHVkEx\r\n"  \
"DDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRNLmNvbTEgMB4GCSqGSIb3\r\n"  \
"DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\r\n"  \
"ggEKAoIBAQDYoUySKC7oaQqRfxCL3kbS7/g+cCTYlePwB5Ooj9bOfS624vs6qRF6\r\n"  \
"j3O5ADCBw7jcVH/BAa2Rhy0hpKZIREKTl2+0jHrHfGJaIXTx1UNwmFfejWKxGiAB\r\n"  \
"ZVYm6RwX6GXNbLbEhgZo1wDzvki4teckt62FYk1OEGCAXW13G8OZpYC7uLQTbhPb\r\n"  \
"KZpYuvS2WXeqjEHGzjqn2q3Pjzq3vODamYOgjeTgd+1S+MjV+1fY0Z8iXj2T8g67\r\n"  \
"vl+gncoc+bjFb8TAPvChL9NqXFXjathE2GJ31XyMmcTThOf7jH5qO4JTQAHwNaad\r\n"  \
"dvlTN/V4JDj5irSYOv+XPjjRTPk2LUpZAgMBAAGjUDBOMB0GA1UdDgQWBBRHjzkn\r\n"  \
"oaDC9Pi7CGTgCsaU8bCNFDAfBgNVHSMEGDAWgBRHjzknoaDC9Pi7CGTgCsaU8bCN\r\n"  \
"FDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBiCMjZRz1qWt2E50bl\r\n"  \
"uU29zwxlodTSeQfQw9p6h9Fw6nEsC0HVU+3zmqtFStv9Azks+OQpAx2rjhqf7E2i\r\n"  \
"hE6+kaZu07qf0LtGK2YonvYu/t19ssXol45BScZqYEwsT2hOrDQLdj3I8UjE0oE8\r\n"  \
"Q66IozSdYwEEoCSb28ybWf4H5K8gaWgN+4YX7bsZGY2KxNodtVKG37y8ZAVsDQ4Y\r\n"  \
"7jF+DGARFfMWJgFn2JgG5CZU007ESpz4NPecuTraAMUjjp8uaJBrRbQOP+HX+kLX\r\n"  \
"q7q/4PMyY31Byj7nD4WBDGDwFi3m2GmBSgVfcuLhzK8rIYVVUNYWNMnxvWz6PdB0\r\n"  \
"XNBE\r\n"  \
"-----END CERTIFICATE----- "
const char letencryptCaPem[] = LET_ENCRYPT_CA_PEM;

/**
 * if want to use IP address,
 * byte server[] = { XXX,XXX,XXX,XXX };
 * MQTT client(server, 1883, callback);
 * want to use domain name,
 * MQTT client("www.sample.com", 1883, callback);
 * iot.eclipse.org is Eclipse Open MQTT Broker: https://iot.eclipse.org/getting-started
**/
MQTT client("VDMSW.VDM.com", 8883, callback);

// recieve message
void callback(char* topic, byte* payload, unsigned int length) {
    char p[length + 1];
    memcpy(p, payload, length);
    p[length] = NULL;
    String message(p);

    if (message.equals("RED"))
        RGB.color(255, 0, 0);
    else if (message.equals("GREEN"))
        RGB.color(0, 255, 0);
    else if (message.equals("BLUE"))
        RGB.color(0, 0, 255);
    else
        RGB.color(255, 255, 255);
    delay(1000);
}

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }

    //RGB.control(true);

    // enable tls. set Root CA pem file.
    // if you don't use TLS, comment out this line.
    client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
    Serial.println("tls enable");

    // connect to the server
    client.connect("sparkclient");

    // publish/subscribe
    if (client.isConnected()) {
        Serial.println("client connected");
        client.publish("outTopic/message", "hello world");
        client.subscribe("inTopic/message");
    }
}

void loop() {
    if (client.isConnected())
    {
        client.loop();
        Serial.println("Connected!");
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}
```

**Comment by SkyGanfor** [comment]
Here is my code, which is just the a1-example.ino file with some slight modifications:

```
#include "MQTT-TLS.h"

void callback(char* topic, byte* payload, unsigned int length);

#define LET_ENCRYPT_CA_PEM                                              \
"-----BEGIN CERTIFICATE----- \r\n"                                      \
"MIID7zCCAtegAwIBAgIJAJZwRCk+7YG4MA0GCSqGSIb3DQEBCwUAMIGMMQswCQYD\r\n"  \
"VQQGEwJVUzERMA8GA1UECAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRz\r\n"  \
"MQwwCgYDVQQKDANHVkExDDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRN\r\n"  \
"LmNvbTEgMB4GCSqGSIb3DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wIBcNMTgwMzAy\r\n"  \
"MTY1MTEzWhgPMjA2ODAyMTgxNjUxMTNaMIGMMQswCQYDVQQGEwJVUzERMA8GA1UE\r\n"  \
"CAwITWljaGlnYW4xFDASBgNVBAcMC0dyYW5kUmFwaWRzMQwwCgYDVQQKDANHVkEx\r\n"  \
"DDAKBgNVBAsMA0dWQTEWMBQGA1UEAwwNVkRNU1cuVkRNLmNvbTEgMB4GCSqGSIb3\r\n"  \
"DQEJARYRYXNvdXNhQEdWQUlOQy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\r\n"  \
"ggEKAoIBAQDYoUySKC7oaQqRfxCL3kbS7/g+cCTYlePwB5Ooj9bOfS624vs6qRF6\r\n"  \
"j3O5ADCBw7jcVH/BAa2Rhy0hpKZIREKTl2+0jHrHfGJaIXTx1UNwmFfejWKxGiAB\r\n"  \
"ZVYm6RwX6GXNbLbEhgZo1wDzvki4teckt62FYk1OEGCAXW13G8OZpYC7uLQTbhPb\r\n"  \
"KZpYuvS2WXeqjEHGzjqn2q3Pjzq3vODamYOgjeTgd+1S+MjV+1fY0Z8iXj2T8g67\r\n"  \
"vl+gncoc+bjFb8TAPvChL9NqXFXjathE2GJ31XyMmcTThOf7jH5qO4JTQAHwNaad\r\n"  \
"dvlTN/V4JDj5irSYOv+XPjjRTPk2LUpZAgMBAAGjUDBOMB0GA1UdDgQWBBRHjzkn\r\n"  \
"oaDC9Pi7CGTgCsaU8bCNFDAfBgNVHSMEGDAWgBRHjzknoaDC9Pi7CGTgCsaU8bCN\r\n"  \
"FDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBiCMjZRz1qWt2E50bl\r\n"  \
"uU29zwxlodTSeQfQw9p6h9Fw6nEsC0HVU+3zmqtFStv9Azks+OQpAx2rjhqf7E2i\r\n"  \
"hE6+kaZu07qf0LtGK2YonvYu/t19ssXol45BScZqYEwsT2hOrDQLdj3I8UjE0oE8\r\n"  \
"Q66IozSdYwEEoCSb28ybWf4H5K8gaWgN+4YX7bsZGY2KxNodtVKG37y8ZAVsDQ4Y\r\n"  \
"7jF+DGARFfMWJgFn2JgG5CZU007ESpz4NPecuTraAMUjjp8uaJBrRbQOP+HX+kLX\r\n"  \
"q7q/4PMyY31Byj7nD4WBDGDwFi3m2GmBSgVfcuLhzK8rIYVVUNYWNMnxvWz6PdB0\r\n"  \
"XNBE\r\n"  \
"-----END CERTIFICATE----- "
const char letencryptCaPem[] = LET_ENCRYPT_CA_PEM;

/**
 * if want to use IP address,
 * byte server[] = { XXX,XXX,XXX,XXX };
 * MQTT client(server, 1883, callback);
 * want to use domain name,
 * MQTT client("www.sample.com", 1883, callback);
 * iot.eclipse.org is Eclipse Open MQTT Broker: https://iot.eclipse.org/getting-started
**/
MQTT client("myservername", 8883, callback);

// recieve message
void callback(char* topic, byte* payload, unsigned int length) {
    char p[length + 1];
    memcpy(p, payload, length);
    p[length] = NULL;
    String message(p);

    if (message.equals("RED"))
        RGB.color(255, 0, 0);
    else if (message.equals("GREEN"))
        RGB.color(0, 255, 0);
    else if (message.equals("BLUE"))
        RGB.color(0, 0, 255);
    else
        RGB.color(255, 255, 255);
    delay(1000);
}

#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }

    //RGB.control(true);

    // enable tls. set Root CA pem file.
    // if you don't use TLS, comment out this line.
    client.enableTls(letencryptCaPem, sizeof(letencryptCaPem));
    Serial.println("tls enable");

    // connect to the server
    client.connect("sparkclient");

    // publish/subscribe
    if (client.isConnected()) {
        Serial.println("client connected");
        client.publish("outTopic/message", "hello world");
        client.subscribe("inTopic/message");
    }
}

void loop() {
    if (client.isConnected())
    {
        client.loop();
        Serial.println("Connected!");
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}
```

**Comment by SkyGanfor** [comment]
@saket424 Your right, I'm not able to connect to port 8883 without tls enabled. I have another config file for my mosquitto broker using port 1883, which contains the default settings of mosquitto.

The problem is definitely is adding TLS to the broker and photon, as once the broker is halted the photon completely locks up.

My issue is not having the photon turn green after a certain amount of time. I've tested this and had it run for multiple days with no problems. Plus @hirotakaster example has this code which connects to particle once every 24 hours to hold a connection.

```
#define ONE_DAY_MILLIS (24 * 60 * 60 * 1000)
unsigned long lastSync = millis();
void setup() {
    if (millis() - lastSync > ONE_DAY_MILLIS) {
        Particle.syncTime();
        lastSync = millis();
    }
```
I also don't think this is a problem with the "client.isConnected" returning false, as when I bootup the photon without the mqtt broker running, it returns false and displays in the serial monitor "Not Connected". I've also had the broker disconnected the photon due to exceeding timeouts with no problems, and the photon doesn't go into a state of green. This error only happens when I manually stop the mqtt broker myself or the server is shutdown.

To me, its seems that when the broker service is stopped, the photon is not safely disconnected or is not told by the mqtt broker that its going to be disconnected. Looking at the photon on the serial monitor, each loop the photon displays either "Connected" or "Not connected". But when I stop the broker, nothing is displayed on the serial monitor, almost as if the photons code is completely halted wherever it was when the broker stopped running.

I also have to wonder if the "client.isConnected" function is returning true after the broker service is stopped. Then the photon hits the "client.loop()" function and maybe errors out thus causing my problem.

**Comment by SkyGanfor** [comment]
Alright, I did some testing and my hypothesis seems to be correct. Once the broker service has been stopped manually by me, when my photon loops again and executes the line "if(client.isConnected)" it returns a TRUE value even though its not connected! The error then occurs when the photon runs "client.loop" and soon after the photon enters a state of green. I know this due to having a "serial.print" directly before and after I run the "client.loop" function, which helped me to pin point where my code stopped. Here is my loop function:

```
void loop() {
    if (client.isConnected())
    {
        delay(5000);
        Serial.println("Connected!");
        client.loop();
        Serial.println(WiFi.localIP());
    }
    else
    {
        Serial.println("Not Connected...");
    }
    delay(200);
}
```
And here is my serial monitor when stopping the broker service: 

![refpic](https://user-images.githubusercontent.com/22162777/37833203-20c5ae72-2e81-11e8-9d04-157f16a46771.JPG)

As you can see, the "Serial.println(Wifi.localip())" is not displayed on the serial montiar, but the "Serial.println("Connected") is, which is executed before running the client.loop command. To me this means the "client.isConnected" is returning TRUE even after the broker service is stopped.

**Comment by hirotakaster** [comment]
@SkyGanfor 
This issue that you having the problem is based Particle firmware TCP/WiFi stack(TCPClient class) depending on TCP state machine, but I thinking your Photon behavior is not a problem. If you want to check the TCP KeepAlive Timeout more quickly, you should be better to use custom Particle Firmware TCP stack by own.

**Comment by SkyGanfor** [comment]
@hirotakaster Alright, that makes sense. I'll look more into checking that TCP KeepAlive Timeout more quickly. Thanks for your help.
